version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html #wordpress

  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    networks:
      - inception
    expose: ["3306"]
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose: ["9000"]
    volumes:
      - wordpress_vol:/var/www/wordpress
    tty: true

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nicolas/Documents/42/Inception/volumes/wordpress'
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nicolas/Documents/42/Inception/volumes/mariadb'

networks:
  inception:
    driver: bridge