version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure #unless-stopped
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    networks:
      - inception
    expose: ["3306"]
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose: ["9000"]
    ports:
      - "9000:9000"
    volumes:
      - wordpress_vol:/var/www/html
    tty: true

#bonus
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    expose: ["6379"]
    ports:
      - "6379:6379"
    volumes:
      - wordpress_vol:/var/www/html

  ftp-server:
    container_name: ftp-server
    build:
      context: ./requirements/bonus/ftp-server
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    expose: ["21"]
    ports:
      - "21:21"
    volumes:
      - wordpress_vol:/home/nico
    
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose: ["8000"]
    ports:
      - "8000:8000"
  
  cadvisor:
    container_name: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      

  site:
    container_name: site
    build:
      context: ./requirements/bonus/site
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    expose: ["1111"]
    ports:
      - "1111:1111"
    volumes:
      - wordpress_vol:/var/www/html

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlesage/data/wordpress_volume'
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlesage/data/mariadb_volume'

networks:
  inception:
    driver: bridge